# Generated by Django 5.2.4 on 2025-08-02 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Classifieds Category',
                'verbose_name_plural': 'Classifieds Categories',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id'], name='classifieds_id_e9930d_idx'), models.Index(fields=['name'], name='classifieds_name_c4d091_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassifiedsAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_advertisements', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_advertisements', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='classifieds_app.classifiedscategory')),
            ],
            options={
                'verbose_name': 'Classifieds Advertisement',
                'verbose_name_plural': 'Classifieds Advertisements',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserAdvertisementLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='classifieds_app.classifiedsadvertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Advertisement Like',
                'verbose_name_plural': 'User Advertisement Likes',
            },
        ),
        migrations.CreateModel(
            name='UserSavedAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='classifieds_app.classifiedsadvertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Saved Advertisement',
                'verbose_name_plural': 'User Saved Advertisements',
            },
        ),
        migrations.CreateModel(
            name='ClassifiedsAdvertisementComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classifieds_app.classifiedsadvertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classifieds Advertisement Comment',
                'verbose_name_plural': 'Classifieds Advertisement Comments',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['id'], name='classifieds_id_17eadf_idx'), models.Index(fields=['advertisement', 'user'], name='classifieds_adverti_9ef161_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassifiedsAdvertisementImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/classifieds/')),
                ('sequence_number', models.PositiveIntegerField(default=1, help_text='Order of the image in the advertisement')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classifieds_app.classifiedsadvertisement')),
            ],
            options={
                'verbose_name': 'Classifieds Advertisement Image',
                'verbose_name_plural': 'Classifieds Advertisement Images',
                'ordering': ('id', 'sequence_number'),
                'indexes': [models.Index(fields=['id'], name='classifieds_id_9cb65b_idx'), models.Index(fields=['advertisement'], name='classifieds_adverti_18053b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='classifiedsadvertisement',
            index=models.Index(fields=['id'], name='classifieds_id_ba4cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='classifiedsadvertisement',
            index=models.Index(fields=['title'], name='classifieds_title_8c539d_idx'),
        ),
        migrations.AddIndex(
            model_name='classifiedsadvertisement',
            index=models.Index(fields=['category', 'creator'], name='classifieds_categor_64babe_idx'),
        ),
        migrations.AddIndex(
            model_name='useradvertisementlike',
            index=models.Index(fields=['id'], name='classifieds_id_dab339_idx'),
        ),
        migrations.AddIndex(
            model_name='useradvertisementlike',
            index=models.Index(fields=['advertisement'], name='classifieds_adverti_1f7228_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useradvertisementlike',
            unique_together={('user', 'advertisement')},
        ),
        migrations.AddIndex(
            model_name='usersavedadvertisement',
            index=models.Index(fields=['id'], name='classifieds_id_cfd50b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersavedadvertisement',
            index=models.Index(fields=['advertisement'], name='classifieds_adverti_ed6edf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedadvertisement',
            unique_together={('user', 'advertisement')},
        ),
    ]
