class StringConstants:
    SPACE: str = " "
    COMMA: str = ","
    COLON: str = ":"
    SEMICOLON: str = ";"
    DOT: str = "."
    UNDERSCORE: str = "_"
    DASH: str = "-"
    SLASH: str = "/"
    BACKSLASH: str = "\\"
    AT: str = "@"
    HASH: str = "#"
    AMPERSAND: str = "&"
    BLANK: str = ""